// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: NetworkMessageProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace BlockBase.Domain.Protos {

  /// <summary>Holder for reflection information generated from NetworkMessageProto.proto</summary>
  public static partial class NetworkMessageProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for NetworkMessageProto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NetworkMessageProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlOZXR3b3JrTWVzc2FnZVByb3RvLnByb3RvEhdCbG9ja2Jhc2UuRG9tYWlu",
            "LlByb3RvcyLQBgoTTmV0d29ya01lc3NhZ2VQcm90bxJfChJOZXR3b3JrTWVz",
            "c2FnZVR5cGUYASABKA4yQy5CbG9ja2Jhc2UuRG9tYWluLlByb3Rvcy5OZXR3",
            "b3JrTWVzc2FnZVByb3RvLk5ldHdvcmtNZXNzYWdlVHlwZUVudW0SDwoHVmVy",
            "c2lvbhgCIAEoBRIPCgdQYXlsb2FkGAMgASgMEhEKCVB1YmxpY0tleRgEIAEo",
            "CRIRCglTaWduYXR1cmUYBSABKAkSEwoLTWVzc2FnZUhhc2gYBiABKAwSEwoL",
            "RGVzdGluYXRpb24YByABKAki5QQKFk5ldHdvcmtNZXNzYWdlVHlwZUVudW0S",
            "CwoHVW5rbm93bhAAEg8KC1JlcXVlc3RJbmZvEAESIQodUmVxdWVzdFByb2R1",
            "Y2VySWRlbnRpZmljYXRpb24QAhIUChBSZXF1ZXN0Tm9kZXNJbmZvEAMSEQoN",
            "UmVxdWVzdEJsb2NrcxAEEhcKE1JlcXVlc3RCbG9ja0hlYWRlcnMQBRIXChNS",
            "ZXF1ZXN0VHJhbnNhY3Rpb25zEAYSGAoUUmVxdWVzdEN1cnJlbnRIZWlnaHQQ",
            "BxIXChNSZXF1ZXN0TWF4QmxvY2tTaXplEAgSFAoQUmVxdWVzdFByb2R1Y2Vy",
            "cxAJEhgKFFJlcXVlc3RQcm9kdWNlcnNMaXN0EAoSDQoJU2VuZEJsb2NrEAsS",
            "HgoaU2VuZFNlbGVjdGVkQ2FuZGlkYXRlc0luZm8QDBIeChpTZW5kUHJvZHVj",
            "ZXJJZGVudGlmaWNhdGlvbhANEhAKDFNlbmROb2RlSW5mbxAOEhEKDVNlbmRO",
            "b2Rlc0luZm8QDxISCg5TZW5kTWluZWRCbG9jaxAQEg4KClNlbmRCbG9ja3MQ",
            "ERIUChBTZW5kQmxvY2tIZWFkZXJzEBISEwoPU2VuZFRyYW5zYWN0aW9uEBMS",
            "FAoQU2VuZFRyYW5zYWN0aW9ucxAUEhUKEVNlbmRDdXJyZW50SGVpZ2h0EBUS",
            "GwoXU2VuZEN1cnJlbnRNYXhCbG9ja1NpemUQFhIWChJTZWFyY2hRdWVyeVJl",
            "cXVlc3QQFxITCg9TZW5kUXVlcnlSZXN1bHQQGBIICgRQaW5nEBkSCAoEUG9u",
            "ZxAaYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::BlockBase.Domain.Protos.NetworkMessageProto), global::BlockBase.Domain.Protos.NetworkMessageProto.Parser, new[]{ "NetworkMessageType", "Version", "Payload", "PublicKey", "Signature", "MessageHash", "Destination" }, null, new[]{ typeof(global::BlockBase.Domain.Protos.NetworkMessageProto.Types.NetworkMessageTypeEnum) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class NetworkMessageProto : pb::IMessage<NetworkMessageProto> {
    private static readonly pb::MessageParser<NetworkMessageProto> _parser = new pb::MessageParser<NetworkMessageProto>(() => new NetworkMessageProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NetworkMessageProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::BlockBase.Domain.Protos.NetworkMessageProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetworkMessageProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetworkMessageProto(NetworkMessageProto other) : this() {
      networkMessageType_ = other.networkMessageType_;
      version_ = other.version_;
      payload_ = other.payload_;
      publicKey_ = other.publicKey_;
      signature_ = other.signature_;
      messageHash_ = other.messageHash_;
      destination_ = other.destination_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetworkMessageProto Clone() {
      return new NetworkMessageProto(this);
    }

    /// <summary>Field number for the "NetworkMessageType" field.</summary>
    public const int NetworkMessageTypeFieldNumber = 1;
    private global::BlockBase.Domain.Protos.NetworkMessageProto.Types.NetworkMessageTypeEnum networkMessageType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::BlockBase.Domain.Protos.NetworkMessageProto.Types.NetworkMessageTypeEnum NetworkMessageType {
      get { return networkMessageType_; }
      set {
        networkMessageType_ = value;
      }
    }

    /// <summary>Field number for the "Version" field.</summary>
    public const int VersionFieldNumber = 2;
    private int version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    /// <summary>Field number for the "Payload" field.</summary>
    public const int PayloadFieldNumber = 3;
    private pb::ByteString payload_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Payload {
      get { return payload_; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "PublicKey" field.</summary>
    public const int PublicKeyFieldNumber = 4;
    private string publicKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PublicKey {
      get { return publicKey_; }
      set {
        publicKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Signature" field.</summary>
    public const int SignatureFieldNumber = 5;
    private string signature_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Signature {
      get { return signature_; }
      set {
        signature_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "MessageHash" field.</summary>
    public const int MessageHashFieldNumber = 6;
    private pb::ByteString messageHash_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString MessageHash {
      get { return messageHash_; }
      set {
        messageHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Destination" field.</summary>
    public const int DestinationFieldNumber = 7;
    private string destination_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Destination {
      get { return destination_; }
      set {
        destination_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NetworkMessageProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NetworkMessageProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NetworkMessageType != other.NetworkMessageType) return false;
      if (Version != other.Version) return false;
      if (Payload != other.Payload) return false;
      if (PublicKey != other.PublicKey) return false;
      if (Signature != other.Signature) return false;
      if (MessageHash != other.MessageHash) return false;
      if (Destination != other.Destination) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (NetworkMessageType != 0) hash ^= NetworkMessageType.GetHashCode();
      if (Version != 0) hash ^= Version.GetHashCode();
      if (Payload.Length != 0) hash ^= Payload.GetHashCode();
      if (PublicKey.Length != 0) hash ^= PublicKey.GetHashCode();
      if (Signature.Length != 0) hash ^= Signature.GetHashCode();
      if (MessageHash.Length != 0) hash ^= MessageHash.GetHashCode();
      if (Destination.Length != 0) hash ^= Destination.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (NetworkMessageType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) NetworkMessageType);
      }
      if (Version != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Version);
      }
      if (Payload.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Payload);
      }
      if (PublicKey.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PublicKey);
      }
      if (Signature.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Signature);
      }
      if (MessageHash.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(MessageHash);
      }
      if (Destination.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Destination);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (NetworkMessageType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) NetworkMessageType);
      }
      if (Version != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Version);
      }
      if (Payload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
      }
      if (PublicKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PublicKey);
      }
      if (Signature.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Signature);
      }
      if (MessageHash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(MessageHash);
      }
      if (Destination.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Destination);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NetworkMessageProto other) {
      if (other == null) {
        return;
      }
      if (other.NetworkMessageType != 0) {
        NetworkMessageType = other.NetworkMessageType;
      }
      if (other.Version != 0) {
        Version = other.Version;
      }
      if (other.Payload.Length != 0) {
        Payload = other.Payload;
      }
      if (other.PublicKey.Length != 0) {
        PublicKey = other.PublicKey;
      }
      if (other.Signature.Length != 0) {
        Signature = other.Signature;
      }
      if (other.MessageHash.Length != 0) {
        MessageHash = other.MessageHash;
      }
      if (other.Destination.Length != 0) {
        Destination = other.Destination;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            networkMessageType_ = (global::BlockBase.Domain.Protos.NetworkMessageProto.Types.NetworkMessageTypeEnum) input.ReadEnum();
            break;
          }
          case 16: {
            Version = input.ReadInt32();
            break;
          }
          case 26: {
            Payload = input.ReadBytes();
            break;
          }
          case 34: {
            PublicKey = input.ReadString();
            break;
          }
          case 42: {
            Signature = input.ReadString();
            break;
          }
          case 50: {
            MessageHash = input.ReadBytes();
            break;
          }
          case 58: {
            Destination = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the NetworkMessageProto message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum NetworkMessageTypeEnum {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("RequestInfo")] RequestInfo = 1,
        [pbr::OriginalName("RequestProducerIdentification")] RequestProducerIdentification = 2,
        [pbr::OriginalName("RequestNodesInfo")] RequestNodesInfo = 3,
        [pbr::OriginalName("RequestBlocks")] RequestBlocks = 4,
        [pbr::OriginalName("RequestBlockHeaders")] RequestBlockHeaders = 5,
        [pbr::OriginalName("RequestTransactions")] RequestTransactions = 6,
        [pbr::OriginalName("RequestCurrentHeight")] RequestCurrentHeight = 7,
        [pbr::OriginalName("RequestMaxBlockSize")] RequestMaxBlockSize = 8,
        [pbr::OriginalName("RequestProducers")] RequestProducers = 9,
        [pbr::OriginalName("RequestProducersList")] RequestProducersList = 10,
        [pbr::OriginalName("SendBlock")] SendBlock = 11,
        [pbr::OriginalName("SendSelectedCandidatesInfo")] SendSelectedCandidatesInfo = 12,
        [pbr::OriginalName("SendProducerIdentification")] SendProducerIdentification = 13,
        [pbr::OriginalName("SendNodeInfo")] SendNodeInfo = 14,
        [pbr::OriginalName("SendNodesInfo")] SendNodesInfo = 15,
        [pbr::OriginalName("SendMinedBlock")] SendMinedBlock = 16,
        [pbr::OriginalName("SendBlocks")] SendBlocks = 17,
        [pbr::OriginalName("SendBlockHeaders")] SendBlockHeaders = 18,
        [pbr::OriginalName("SendTransaction")] SendTransaction = 19,
        [pbr::OriginalName("SendTransactions")] SendTransactions = 20,
        [pbr::OriginalName("SendCurrentHeight")] SendCurrentHeight = 21,
        [pbr::OriginalName("SendCurrentMaxBlockSize")] SendCurrentMaxBlockSize = 22,
        [pbr::OriginalName("SearchQueryRequest")] SearchQueryRequest = 23,
        [pbr::OriginalName("SendQueryResult")] SendQueryResult = 24,
        [pbr::OriginalName("Ping")] Ping = 25,
        [pbr::OriginalName("Pong")] Pong = 26,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
